spring:
  application:
    name: microservice-api-gateway
server:
  port: 8050
  serverPath:/zuul
eureka:
  instance:
    hostname: gateway
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
zuul:
  routes:
    movie:                                                           
      path: /**                                                 # 想要映射到的路径
      service-id: microservice-provider-user
