server:
  port: 11022

spring:
  application:
    name: microservice-zipkin-stream-client-backend

 #rabbitmq配置
  rabbitmq:
    host: 127.0.0.1
    port : 5672
    username: guest
    password: guest

