spring:
  application:
    name: eureka-server
server:
  port: 7761
eureka:
  healthcheck:
    enabled: true
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000
  instance: 
    hostname: peer1
  client:
    service-url:
      defaultZone: http://peer2:8761/eureka/,http://peer3:9761/eureka/