eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 6
  client:
    registerWithEureka: false
    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#      zhqh: http://localhost-2:8762/eureka/
spring:
  application:
    name: eureka-server
---
spring:
  profiles: profile1
eureka.instance.hostname: localhost-1
server.port: 8761
---
spring:
  profiles: profile2
eureka.instance.hostname: localhost-2
server.port: 8762
---
spring:
  profiles: profile3
eureka.instance.hostname: localhost-3
server.port: 8763