#:wprofile:default add some code
hello:
     a: AcC1
     b: Bcd1
     c: Cdwe42
servers:
  jpushCenter:
    host: http://127.0.0.1:8050/jpush/send/send/s
    title: GitHub50-云端钱包测试版ad
    destination: GitHub50-ydWalletTestAsdf

apply:
  message: GitHub50-local messagedd
